import assert from 'node:assert/strict';
import { test } from 'node:test';
import { captainIntent } from '../src/advice.js';
import { defaults } from '../src/config.js';
import { initPhysics, newCareer, Simulation } from '../src/simulation.js';

await initPhysics();
const fixture = () => new Simulation(defaults(), newCareer(), { training: true });
test('Weapon readiness explains missing targets, depth, range, ammunition, reload, and paused patrols', () => {
  const s = fixture();
  assert.match(s.weaponReadiness('torpedo').reason, /contact/);
  const ship = s.addShip(s.p.x + 300, s.p.z - 400, 0);
  s.targetId = ship.id;
  assert.equal(s.weaponReadiness('torpedo').ready, true);
  s.p.depth = 80;
  assert.match(s.weaponReadiness('torpedo').reason, /Too deep/);
  assert.match(s.weaponReadiness('gun').reason, /surface/);
  s.p.depth = 0;
  s.p.torpedoes = 0;
  assert.match(s.weaponReadiness('torpedo').reason, /resupply/);
  s.p.torpedoes = 14;
  s.cooldown = 3;
  assert.match(s.weaponReadiness('torpedo').reason, /Reloading/);
  s.cooldown = 0;
  ship.x = s.p.x + 10000;
  assert.match(s.weaponReadiness('torpedo').reason, /range/);
  s.paused = true;
  const ammo = s.p.torpedoes;
  assert.equal(s.fireTorpedo(), false);
  assert.equal(s.p.torpedoes, ammo);
  s.dispose();
});
test('Captain advice prioritizes depleted underwater resources and escorts ahead of attack opportunities', () => {
  const s = fixture();
  const ship = s.addShip(s.p.x + 300, s.p.z - 400, 0);
  s.targetId = ship.id;
  assert.equal(captainIntent(s).action, 'scope');
  s.p.depth = 12;
  assert.equal(captainIntent(s).action, 'torpedo');
  s.detected = true;
  assert.equal(captainIntent(s).action, 'deep');
  s.p.battery = 10;
  assert.equal(captainIntent(s).action, 'surface');
  s.paused = true;
  assert.equal(captainIntent(s).action, 'resume');
  s.dispose();
});
test('Underwater resource alerts stop compressed travel, report once, and rearm after replenishment', () => {
  const s = fixture();
  s.p.depth = 12;
  s.p.targetDepth = 12;
  s.p.battery = 14;
  s.acceleration = 1000;
  s.update(0.1);
  assert.equal(s.acceleration, 1);
  const first = s.p.log.filter((e) => e.text.includes('Battery below')).length;
  assert.equal(first, 1);
  for (let i = 0; i < 30; i++) s.update(1 / 30);
  assert.equal(s.p.log.filter((e) => e.text.includes('Battery below')).length, 1);
  s.p.battery = 100;
  s.warnResources();
  s.p.battery = 14;
  s.warnResources();
  assert.equal(s.p.log.filter((e) => e.text.includes('Battery below')).length, 2);
  s.dispose();
});
